repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        stages: [pre-commit]

