#!/bin/bash
# Upload CSV generated by the LLVM pass to a PostgreSQL database
# Usage: ./upload_to_db.sh <postgres_connection_string> [input_csv] [--validate]

set -e

CONN_STR="${1:-}"
INPUT_CSV="${2:-basicblocks.csv}"
RUN_VALIDATION=false

# Check for --validate flag
if [ "$3" = "--validate" ] || [ "$2" = "--validate" ]; then
    RUN_VALIDATION=true
    if [ "$2" = "--validate" ]; then
        INPUT_CSV="basicblocks.csv"
    fi
fi

if [ -z "$CONN_STR" ]; then
    echo "Usage: $0 <postgres_connection_string> [input_csv] [--validate]"
    echo ""
    echo "Example:"
    echo "  $0 'postgresql://user:password@host/db' basicblocks.csv"
    echo "  $0 'postgresql://user:password@host/db' data/ir_analysis_basicblocks.csv --validate"
    echo ""
    exit 1
fi

if [ ! -f "$INPUT_CSV" ]; then
    echo "Error: Input file '$INPUT_CSV' not found!"
    exit 1
fi

# Validate CSV header
EXPECTED_HEADER="function_name,basicblock_id,has_tracing_call,number_of_instructions,instructions"
ACTUAL_HEADER=$(head -n 1 "$INPUT_CSV")

if [ "$ACTUAL_HEADER" != "$EXPECTED_HEADER" ]; then
    echo "Error: CSV header does not match expected format!"
    echo ""
    echo "Expected: $EXPECTED_HEADER"
    echo "Actual:   $ACTUAL_HEADER"
    echo ""
    exit 1
fi

FULL_PATH="$(cd "$(dirname "$INPUT_CSV")" && pwd)/$(basename "$INPUT_CSV")"

echo ""
echo "→ Uploading to database..."
psql "${CONN_STR}" << SQL
TRUNCATE basicblocks RESTART IDENTITY;
\copy basicblocks (function_name, basicblock_id, has_tracing_call, number_of_instructions, instructions) FROM '${FULL_PATH}' DELIMITER ',' CSV HEADER
SELECT COUNT(*) AS total_rows FROM basicblocks;
SQL

echo ""
echo "✓ Upload complete!"

# Run validation if requested
if [ "$RUN_VALIDATION" = true ]; then
    echo ""
    echo "→ Running validation checks..."
    python3 validate_data.py "$CONN_STR"
fi

echo ""
