#!/bin/bash
# Upload CSV generated by the LLVM pass to a PostgreSQL database
# Usage: ./upload.sh <postgres_connection_string> [input_csv]

set -e

CONN_STR="${1:-}"
INPUT_CSV="${2:-basicblocks.csv}"

if [ -z "$CONN_STR" ]; then
    echo "Usage: $0 <postgres_connection_string> [input_csv]"
    echo ""
    echo "Example:"
    echo "  $0 'postgresql://user:password@host/db' basicblocks.csv"
    echo ""
    exit 1
fi

if [ ! -f "$INPUT_CSV" ]; then
    echo "Error: Input file '$INPUT_CSV' not found!"
    exit 1
fi

# Validate CSV header
EXPECTED_HEADER="function_name,basicblock_id,has_tracing_call,number_of_instructions,instructions"
ACTUAL_HEADER=$(head -n 1 "$INPUT_CSV")

if [ "$ACTUAL_HEADER" != "$EXPECTED_HEADER" ]; then
    echo "Error: CSV header does not match expected format!"
    echo ""
    echo "Expected: $EXPECTED_HEADER"
    echo "Actual:   $ACTUAL_HEADER"
    echo ""
    exit 1
fi

FULL_PATH="$(cd "$(dirname "$INPUT_CSV")" && pwd)/$(basename "$INPUT_CSV")"

echo ""
echo "→ Uploading to database..."
psql "${CONN_STR}" << SQL
TRUNCATE basicblocks RESTART IDENTITY;
\copy basicblocks (function_name, basicblock_id, has_tracing_call, number_of_instructions, instructions) FROM '${FULL_PATH}' DELIMITER ',' CSV HEADER
SELECT COUNT(*) AS total_rows FROM basicblocks;
SQL
