#!/bin/bash
# Upload CSV generated by the LLVM pass to a PostgreSQL database
# Usage: ./upload.sh <postgres_connection_string> [input_csv]

set -e

CONN_STR="${1:-}"
INPUT_CSV="${2:-basicblocks.csv}"
CLEAN_CSV="basicblocks_clean.csv"

if [ -z "$CONN_STR" ]; then
    echo "Usage: $0 <postgres_connection_string> [input_csv]"
    echo ""
    echo "Example:"
    echo "  $0 'postgresql://user:password@host/db' basicblocks.csv"
    echo ""
    exit 1
fi

if [ ! -f "$INPUT_CSV" ]; then
    echo "Error: Input file '$INPUT_CSV' not found!"
    exit 1
fi

# Step 1: Clean and deduplicate the CSV
echo "→ Cleaning and deduplicating CSV..."
python3 cleanup_csv.py "$INPUT_CSV" "$CLEAN_CSV"

if [ ! -f "$CLEAN_CSV" ]; then
    echo "Error: Failed to create cleaned CSV!"
    exit 1
fi

# Step 2: Get full path for \copy command
FULL_PATH="$(cd "$(dirname "$CLEAN_CSV")" && pwd)/$(basename "$CLEAN_CSV")"

echo ""
echo "→ Uploading to database..."
psql "${CONN_STR}" << SQL
TRUNCATE basicblocks RESTART IDENTITY;
\copy basicblocks (function_name, basicblock_id, has_tracing_call, number_of_instructions, instructions) FROM '${FULL_PATH}' DELIMITER ',' CSV HEADER
SELECT COUNT(*) AS total_rows FROM basicblocks;
SQL

echo ""
echo "✓ Upload complete!"
echo "  - Cleaned CSV: $CLEAN_CSV"
echo ""